# Generated by Django 5.1.1 on 2024-09-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_receipe_delete_car_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(upload_to='receipe/'),
        ),
    ]
